name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  this:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: make
        run: |
          make
